#! /bin/sh

bash /home/luke.arntz/.screenlayout/three-screens.sh
sleep 3

xset +fp /home/luke.arntz/.local/share/fonts
xset fp rehash

GTK_THEME=Adwaita:dark
export GTK_THEME

XDG_DATA_DIRS="$XDG_DATA_DIRS"
export XDG_DATA_DIRS

systemctl --user import-environment DISPLAY # for clipmenud

if [ -x "$(command -v redshift)" ]; then
  pkill redshift
  redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq '.location.lat, .location.lng' | tr '\n' ':' | sed 's/:$//') -b 1:0.80 -P & disown
fi

# set a wallpaper
$HOME/.config/bspwm/random-wallpaper.sh $HOME/Pictures/Wallpapers

wmname LG3D # for java stuff like intellij https://www.reddit.com/r/bspwm/comments/267srd/problem_with_intellij_bspwm/
polybar primary & disown
picom & disown
# polybar dp2 & disown
dunst & disown
sxhkd & disown
clipmenud & 
#pasystray &

bspc monitor eDP-1-1 -d 1 2
bspc monitor DP-1-2-1 -d 3 4 5 6
bspc monitor DP-1-2-2 -d 7 8 9 10

bspc config border_width           1
bspc config window_gap             0 
bspc config active_border_color '#282828'
bspc config focused_border_color '#282828'
bspc config normal_border_color '#1d2021'
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Evolution-alarm-notify state=floating 
bspc rule -a vmrc state=floating
bspc rule -a zoom state=floating
bspc rule -a firefox:Toolkit border=off sticky=on state=floating
bspc rule -a Gnome-calculator state=floating
